version: '3'
services:
  vue-app:
    build: "./vue.Dockerfile"
    ports:
      - "3000:3000"
    volumes:
      - "./vue-app/src:/app/src"
    depends_on:
      - spring-boot-app

  spring-boot-app:
    build: "Dockerfile"
    ports:
      - "8080:8080"